### ISSUE TITLE
Reverse Engineering

### ISSUE THREAD

**Issue by DanielaPavia** [WomenPlusPlus/deploy-impact-22-openedu-c#2]
We had a look at the Openedu webpage and DB with the objective of understanding what is the scope of the project. what are the flaws of the existing prototype and get some ideas on what functionalities we think could be improved

**Comment by DanielaPavia** [comment]
Some of our finds are:
1. it can be a nice to have if the person uploading the projects has the possibility to leave some open contact Information that is included in the overview of the project.
2. There is no defined structure to the filter of the language. This feature needs to be analysed in more detail. Is it important to show only the projects if the original data resides on the internet in the given language or should it be included only of the openedu webpage has a description translated in the filtering language
3. The search engine only looks for keywords in the title and subtile of the database. We consider this search should be extended to look in the short and full description of the projects.
4. What is the colours assigned to the different projects? are those giving any information?
5. there are som url links not working

**Comment by kezihlmann** [comment]
We understand the openedu.ch website
